# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e26f08f55690def1e52e41c70fd352e60cece7b924ca63f3234cc0a7b683033f3510fd35caf3f82e5d443c15117ac716e8f8ca8e2df930c677895f36c24236c3

test:
  secret_key_base: 5f2c85cb9653a88f2bcd4a39a0c8658577f8b027f95d9f2458c5ed9102fca8aaceee01cf7815f19a74f95fff737c5f24ec68927d215275a03f04de2d829b1af5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
